services:
  openbadges-server:
    image: ghcr.io/rollercoaster-dev/openbadges-modular-server:latest
    platform: linux/amd64
    container_name: openbadges_modular_server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - BASE_URL=http://localhost:3000
      - DB_TYPE=sqlite
      - SQLITE_FILE=/app/data/openbadges.sqlite
      - AUTH_ENABLED=true
      - JWT_SECRET=dev-secret-please-change
      - AUTH_API_KEY_ENABLED=true
      - AUTH_API_KEY_SYSTEM=test-api-key-123:system-user:System integration
      - AUTH_BASIC_AUTH_ENABLED=true
      - AUTH_BASIC_AUTH_ADMIN=admin:admin-user:Administrator
      - LOG_LEVEL=debug
    volumes:
      - ./openbadges_server_data:/app/data
