services:
  openbadges-server:
    image: ghcr.io/rollercoaster-dev/openbadges-modular-server:latest
    container_name: openbadges_modular_server
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      # Server configuration
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - HOST=${HOST:-0.0.0.0}
      - BASE_URL=${OPENBADGES_SERVER_URL:-http://localhost:3000}

      # Database configuration (SQLite)
      - DB_TYPE=${DB_TYPE:-sqlite}
      - SQLITE_FILE=${SQLITE_FILE:-/data/openbadges.sqlite}

      # Authentication configuration
      - AUTH_ENABLED=${OPENBADGES_AUTH_ENABLED:-true}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-please-change}
      - AUTH_API_KEY_SYSTEM=${OPENBADGES_API_KEY:-test-api-key-123}:system-user:System integration
      - AUTH_BASIC_AUTH_ADMIN=${OPENBADGES_BASIC_AUTH_USER:-admin}:${OPENBADGES_BASIC_AUTH_PASS:-admin-user}:Administrator

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-pretty}
    volumes:
      - sqlite_data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/app/health-check.sh']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'

volumes:
  sqlite_data:
