name: 'Validate OpenBadges Compliance'
description: 'Validates changes for OpenBadges specification compliance'

inputs:
  pr-files:
    description: 'Comma-separated list of changed files in the PR'
    required: false

outputs:
  compliance-status:
    description: 'Overall compliance status (pass/fail/warning)'
  issues-found:
    description: 'Number of compliance issues found'

runs:
  using: 'node20'
  main: 'index.js'
