name: Bug Report
description: Report a bug or issue in the OpenBadges system
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: input
    id: task-id
    attributes:
      label: Related Task ID
      description: Internal task UUID (if applicable)
      placeholder: "UUID from task list"
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which system component is affected?
      options:
        - Authentication
        - Badge Management
        - Verification
        - User Management
        - API
        - Frontend
        - Compliance
        - Security
        - Documentation
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
      placeholder: "What is the bug? How does it affect OpenBadges functionality?"
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter badge data '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen according to OpenBadges specification?
      placeholder: "Describe the expected behavior, including any relevant OpenBadges spec requirements"
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Describe what actually occurs, including error messages"
    validations:
      required: true
      
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: "Browser, OS, Node version, etc."
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable, security issue)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true
      
  - type: dropdown
    id: openbadges-compliance
    attributes:
      label: OpenBadges Compliance Impact
      description: Does this bug affect OpenBadges specification compliance?
      options:
        - "Yes - Breaks compliance"
        - "Yes - Affects compliance"
        - "No - Internal issue only"
        - "Unknown"
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, logs, or context
      placeholder: "Add any other context about the problem here, including logs or screenshots"
    validations:
      required: false
      
  - type: checkboxes
    id: security-impact
    attributes:
      label: Security Impact
      description: Check if this bug has security implications
      options:
        - label: This bug may have security implications
        - label: This bug affects credential verification
        - label: This bug involves user data handling
