name: Feature Request
description: Create a new feature implementation for OpenBadges system
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: input
    id: task-id
    attributes:
      label: Task ID
      description: Internal task UUID (if applicable)
      placeholder: "UUID from task list"
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which system component does this affect?
      options:
        - Authentication
        - Badge Management
        - Verification
        - User Management
        - API
        - Frontend
        - Compliance
        - Security
        - Documentation
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the feature
      placeholder: "What should this feature do? How does it relate to OpenBadges functionality?"
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what constitutes completion
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] OpenBadges compliance verified
        - [ ] Security review completed
        - [ ] Tests added and passing
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: input
    id: estimate
    attributes:
      label: Time Estimate
      description: Estimated development time
      placeholder: "e.g., 2 days, 1 week"
      
  - type: dropdown
    id: openbadges-version
    attributes:
      label: OpenBadges Version
      description: Which OpenBadges specification version does this relate to?
      options:
        - OpenBadges 2.x
        - OpenBadges 3.0
        - Both
        - Not Applicable
    validations:
      required: false
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations, dependencies, or implementation notes
      placeholder: "Dependencies, API changes, database schema changes, etc."
    validations:
      required: false
      
  - type: checkboxes
    id: compliance-checklist
    attributes:
      label: Compliance Considerations
      description: Check all that apply
      options:
        - label: Requires OpenBadges specification compliance review
        - label: Involves cryptographic operations
        - label: Handles user personal data
        - label: Affects badge verification process
        - label: Changes API endpoints
        - label: Requires security audit
