/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BadgeCard: typeof import('./components/Badge/BadgeCard.vue')['default']
    Breadcrumb: typeof import('./components/Navigation/Breadcrumb.vue')['default']
    LoginForm: typeof import('./components/Auth/LoginForm.vue')['default']
    MainNavigation: typeof import('./components/Navigation/MainNavigation.vue')['default']
    OAuthProviderButton: typeof import('./components/Auth/OAuthProviderButton.vue')['default']
    RegisterForm: typeof import('./components/Auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCard: typeof import('./components/User/UserCard.vue')['default']
    UserForm: typeof import('./components/User/UserForm.vue')['default']
    UserList: typeof import('./components/User/UserList.vue')['default']
    UserMenu: typeof import('./components/Navigation/UserMenu.vue')['default']
    UserSearch: typeof import('./components/User/UserSearch.vue')['default']
  }
}
